name: schemafx
description: 'Build Without Boundaries.'
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.0.0
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  flutter_draggable_gridview: ^0.0.14
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  expressions: ^0.2.2
  uuid: ^4.0.0
  csv: ^5.0.1
  side_sheet: ^1.0.4+1
  http: ^1.2.2
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.0
  web: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Icon-32.png
    - assets/icons/Icon-192.png
    - assets/icons/Icon-512.png
